### ISSUE TITLE
US 06.02.01 As an experimenter, I want to add Geo-location to experimental trials that need it.

### ISSUE THREAD

**Issue by arrooney** [CMPUT301W21T05/KrowdTrialz#24]
## Rationale

Some experiments require geo-locations. If, as an experimenter, one wishes to contribute to one of these experiments, a location must be associated with the trial.

## TODO
- [ ] Add way to enter, or automatically populate location data from user
- [ ] Add location field to trial object

**Comment by arrooney** [comment]
## Rationale:

Some experiments require geo-locations. If, as an experimenter, one wishes to contribute to one of these experiments, a location must be associated with the trial.

## Needed
- [ ] Add location field to trial object
- [ ] Add way to enter, or automatically populate location data from user
